script.sql
use BANHANG_TT_INDEX;
CREATE NONCLUSTERED INDEX idx_dh_01
ON DONHANG (MATX)
INCLUDE (NGAYLAP,PHIVC)
WHERE TINHTRANG='TRUE';

use BANHANG_TT_INDEX;
CREATE NONCLUSTERED INDEX idx_dh_02
ON DONHANG (MADT)
INCLUDE (NGAYLAP,TONGTIEN,PHIVC)
WHERE TINHTRANG='TRUE';


USE BANHANG_TT;
Select  DATEADD(MONTH, DATEDIFF(MONTH, 0, NGAYLAP), 0), count( DISTINCT MADH) as tong_don, sum(PHIVC) as thu_nhap from DONHANG WHERE MATX = 'MATX27' AND TINHTRANG = 'TRUE' AND DATEADD(MONTH, DATEDIFF(MONTH, 0, NGAYLAP), 0) 
= '2020-12-01 00:00:00.000'  GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, NGAYLAP), 0) 

USE BANHANG_TT_INDEX;
Select  DATEADD(MONTH, DATEDIFF(MONTH, 0, NGAYLAP), 0), count( DISTINCT MADH) as tong_don, sum(PHIVC) as thu_nhap from DONHANG WHERE MATX = 'MATX27' AND TINHTRANG = 'TRUE' AND DATEADD(MONTH, DATEDIFF(MONTH, 0, NGAYLAP), 0) 
= '2020-12-01 00:00:00.000'  GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, NGAYLAP), 0) 


USE BANHANG_TT;
Select  DATEADD(MONTH, DATEDIFF(MONTH, 0, NGAYLAP), 0), count(MADH) as tong_don, sum(TONGTIEN - PHIVC) as thu_nhap from DONHANG WHERE MADT = 'MADT14' AND TINHTRANG = 'TRUE' AND DATEADD(MONTH, DATEDIFF(MONTH, 0, NGAYLAP), 0) 
= '2020-12-01 00:00:00.000'  GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, NGAYLAP), 0) 

USE BANHANG_TT_INDEX;
Select  DATEADD(MONTH, DATEDIFF(MONTH, 0, NGAYLAP), 0), count(MADH) as tong_don, sum(TONGTIEN - PHIVC) as thu_nhap from DONHANG WHERE MADT = 'MADT14' AND TINHTRANG = 'TRUE' AND DATEADD(MONTH, DATEDIFF(MONTH, 0, NGAYLAP), 0) 
= '2020-12-01 00:00:00.000'  GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, NGAYLAP), 0) 

use BANHANG_TT;
CREATE NONCLUSTERED INDEX idx_tx_01 
ON TAIXE (TEN_TK);
CREATE NONCLUSTERED INDEX idx_ph_01 
ON PHANHOI (MAKH);
CREATE NONCLUSTERED INDEX idx_ph_02 
ON PHANHOI (MAMA);
CREATE NONCLUSTERED INDEX idx_kh_01 
ON KHACHHANG (TEN_TK);
CREATE NONCLUSTERED INDEX idx_ma_01 
ON MONAN (MACH);
CREATE NONCLUSTERED INDEX idx_dt_01 
ON DOITAC (TEN_TK);
CREATE NONCLUSTERED INDEX idx_dh_02 
ON DONHANG (MAKH);
CREATE NONCLUSTERED INDEX idx_dh_03 
ON DONHANG (MATX);
CREATE NONCLUSTERED INDEX idx_dh_04 
ON DONHANG (MADT);
CREATE NONCLUSTERED INDEX idx_tt_01 
ON THANHTOAN (MADH);
CREATE NONCLUSTERED INDEX idx_hd_01 
ON HOPDONG (MADT);
CREATE NONCLUSTERED INDEX idx_hd_02 
ON HOPDONG (MANV);
CREATE NONCLUSTERED INDEX idx_hd_03 
ON HOPDONG (THOIGIANHIEULUC);
CREATE NONCLUSTERED INDEX idx_nv_01 
ON NHANVIEN (TEN_TK);